#ifndef OPENMW_VERSION_HPP
#define OPENMW_VERSION_HPP

#define TES3MP_VERSION "0.7.0-alpha"
#define TES3MP_PROTO_VERSION 7

#define TES3MP_DEFAULT_PASSW "SuperPassword"
#define TES3MP_MASTERSERVER_PASSW "12345"

#define TES3MP_CREDITS_CHECKSUM "02003664"

#endif //OPENMW_VERSION_HPP
