#ifndef OPENMW_VERSION_HPP
#define OPENMW_VERSION_HPP

#define TES3MP_VERSION "0.7.1"
#define TES3MP_PROTO_VERSION 8

#define TES3MP_DEFAULT_PASSW "SuperPassword"
#define TES3MP_MASTERSERVER_PASSW "12345"

#define TES3MP_CREDITS_CHECKSUM "C1F1317F"


#endif //OPENMW_VERSION_HPP
